name: run-tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        # Disable testing on windows for now...
        # os: [ubuntu-latest, windows-latest]
        os: [ubuntu-latest]
        php: [7.4, 8.0, 8.1]
        laravel: [7.*, 8.*, 9.*]
        #stability: [prefer-lowest, prefer-stable]
        stability: [prefer-stable]
        include:
          - laravel: 7.*
            testbench: 5.*
          - laravel: 8.*
            testbench: ^6.6
          - laravel: 9.*
            testbench: 7.*
        # Laravel 7 has no support for PHP 8.1
        exclude:
          - laravel: 7.*
            php: 8.1
          # Older versions of L7 doesn't support PHP 8
          - laravel: 7.*
            php: 8
            stability: prefer-lowest
          # Laravel 9 doesn't support < PHP 8
          - laravel: 9.*
            php: 7.4

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"
      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction
      - name: Execute tests
        run: vendor/bin/phpunit