name: run-tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        # Disable testing on windows for now...
        # os: [ubuntu-latest, windows-latest]
        os: [ubuntu-latest]
        php: [7.4, 8.0, 8.1, 8.2, 8.3]
        laravel: [7.*, 8.*, 9.*, 10.*, 11.*]
        #stability: [prefer-lowest, prefer-stable]
        stability: [prefer-stable]
        exclude:
          # Older versions of L7 doesn't support PHP 8, 8.1, 8.2 or 8.3
          - laravel: 7.*
            php: 8
            stability: prefer-lowest
          - laravel: 7.*
            php: 8.1
          - laravel: 7.*
            php: 8.2
          - laravel: 7.*
            php: 8.3
          # Laravel 9 doesn't support < PHP 8
          - laravel: 9.*
            php: 7.4
          # Laravel 10 doesn't support < PHP 8.1
          - laravel: 10.*
            php: 7.4
          - laravel: 10.*
            php: 8.0
          # Laravel 11 doesn't support < PHP 8.2
          - laravel: 11.*
            php: 7.4
          - laravel: 11.*
            php: 8.0
          - laravel: 11.*
            php: 8.1

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"
      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction
      - name: Execute tests
        run: vendor/bin/phpunit
